// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertConditionTerm) DeepCopyInto(out *AlertConditionTerm) {
	*out = *in
	out.Duration = in.Duration.DeepCopy()
	out.Threshold = in.Threshold.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertConditionTerm.
func (in *AlertConditionTerm) DeepCopy() *AlertConditionTerm {
	if in == nil {
		return nil
	}
	out := new(AlertConditionTerm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NewRelicAPIKeySecret) DeepCopyInto(out *NewRelicAPIKeySecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NewRelicAPIKeySecret.
func (in *NewRelicAPIKeySecret) DeepCopy() *NewRelicAPIKeySecret {
	if in == nil {
		return nil
	}
	out := new(NewRelicAPIKeySecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NrqlAlertCondition) DeepCopyInto(out *NrqlAlertCondition) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NrqlAlertCondition.
func (in *NrqlAlertCondition) DeepCopy() *NrqlAlertCondition {
	if in == nil {
		return nil
	}
	out := new(NrqlAlertCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NrqlAlertCondition) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NrqlAlertConditionList) DeepCopyInto(out *NrqlAlertConditionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NrqlAlertCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NrqlAlertConditionList.
func (in *NrqlAlertConditionList) DeepCopy() *NrqlAlertConditionList {
	if in == nil {
		return nil
	}
	out := new(NrqlAlertConditionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NrqlAlertConditionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NrqlAlertConditionSpec) DeepCopyInto(out *NrqlAlertConditionSpec) {
	*out = *in
	if in.Terms != nil {
		in, out := &in.Terms, &out.Terms
		*out = make([]AlertConditionTerm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Nrql = in.Nrql
	out.APIKeySecret = in.APIKeySecret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NrqlAlertConditionSpec.
func (in *NrqlAlertConditionSpec) DeepCopy() *NrqlAlertConditionSpec {
	if in == nil {
		return nil
	}
	out := new(NrqlAlertConditionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NrqlAlertConditionStatus) DeepCopyInto(out *NrqlAlertConditionStatus) {
	*out = *in
	if in.AppliedSpec != nil {
		in, out := &in.AppliedSpec, &out.AppliedSpec
		*out = new(NrqlAlertConditionSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NrqlAlertConditionStatus.
func (in *NrqlAlertConditionStatus) DeepCopy() *NrqlAlertConditionStatus {
	if in == nil {
		return nil
	}
	out := new(NrqlAlertConditionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NrqlQuery) DeepCopyInto(out *NrqlQuery) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NrqlQuery.
func (in *NrqlQuery) DeepCopy() *NrqlQuery {
	if in == nil {
		return nil
	}
	out := new(NrqlQuery)
	in.DeepCopyInto(out)
	return out
}
