
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - nrqlalertconditions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - nrqlalertconditions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - policies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - policies/status
  verbs:
  - get
  - patch
  - update
