version: 2.1

orbs:
  snyk: snyk/snyk@0.0.10

workflows:
  integration:
    jobs:
      - checkout_code
      - lint:
          requires:
            - checkout_code
      - test:
          requires:
            - checkout_code
      # Snyk fails, out of memory. Disabled for now
      # - security-scan:
      #     requires:
      #       - checkout_code
      - compile:
          requires:
            - lint
            - test
            # - security-scan
      - hold-for-release:
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
          require:
            - compile
#      - release:
#          filters:
#            branches:
#              ignore: /.*/
#            tags:
#              only: /^v\d+\.\d+\.\d+$/
#          requires:
#            - compile
#            - hold-for-release

jobs:
  checkout_code:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: git fetch --tags
      - run:
          name: Install kubebuilder
          command: |
            version=2.3.1
            arch=amd64
            curl -L -O https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${version}/kubebuilder_${version}_linux_${arch}.tar.gz
            tar -zxvf kubebuilder_${version}_linux_${arch}.tar.gz
            mv kubebuilder_${version}_linux_${arch} ~/kubebuilder
      - save_cache:
          key: repo-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}-test
          paths:
            - ~/project
            - ~/kubebuilder

  lint:
    docker:
      - image: circleci/golang:1.14
    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}-test
      - run:
          name: Lint
          command: make lint

  test:
    docker:
      - image: circleci/golang:1.14
    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}-test
      - run:
          name: Restore kubebuilder
          command: |
            sudo mv ~/kubebuilder /usr/local/kubebuilder
            export PATH=$PATH:/usr/local/kubebuilder/bin
      - run:
          name: Unit Tests
          command: make test-unit
      - run:
          name: Integration Tests
          command: make test-integration

  # security-scan:
  #   docker:
  #     - image: circleci/golang:1.14
  #   steps:
  #     - restore_cache:
  #         key: repo-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}-test
  #     - snyk/scan:
  #         severity-threshold: high
  #         fail-on-issues: false
  #         monitor-on-build: true

  compile:
    docker:
      - image: circleci/golang:1.14
    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}-test
      - run: make compile-only
#  release:
#    docker:
#      - image: circleci/golang:1.14
#    steps:
#      - checkout
#      - setup_remote_docker:
#          docker_layer_caching: true
#      - run: make release-publish
