# Note: If using a k8s secret, remove `api_key`, uncomment `api_key_secret`,
# add your API key to examples/example_secret.yaml, and run
# `kubectl apply -f examples/example_secret.yaml`

apiVersion: nr.k8s.newrelic.com/v1
kind: Policy
metadata:
  name: my-policy
spec:
  name: sblue testing k8s created policy
  incident_preference: "PER_POLICY"
  region: "us"
  api_key: <your New Relic personal API key>
  # api_key_secret:
  #   name: nr-api-key
  #   namespace: default
  #   key_name: api-key
  conditions:
    - spec:
        nrql:
          query: "SELECT count(*) FROM Transactions"
          since_value: "10"
        enabled: true
        terms:
          - threshold: "75.0"
            time_function: "all"
            duration: "5"
            priority: "critical"
            operator: "above"
        name: "K8s generated alert condition"
    - spec:
        nrql:
          query: "SELECT count(*) FROM Transactions"
          since_value: "5"
        enabled: true
        terms:
          - threshold: "150.0"
            time_function: "all"
            duration: "5"
            priority: "critical"
            operator: "above"
        name: "K8s generated alert condition 2"
